# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ernestojv
# "service" is the name of this project. This will also be added to your AWS resource names.
service: dronofy-fc

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [DistributionCenterTable, Arn]
            - Fn::GetAtt: [ProductTable, Arn]
  environment:
    DISTRIBUTIONCENTER_TABLE: DistributionCenterTable
    PRODUCT_TABLE: ProductTable

functions:
  #Distribution Center
  createDistributionCenter:
    handler: src/handlers/distributionCenterHandler.create
    events:
      - http:
          path: distribution-center
          method: post
          cors: true
  getDistributionCenterById:
    handler: src/handlers/distributionCenterHandler.getById
    events:
      - http:
          path: distribution-center/{id}
          method: get
          cors: true
  getDistributionCenters:
    handler: src/handlers/distributionCenterHandler.getAll
    events:
      - http:
          path: distribution-center
          method: get
          cors: true
  #Product
  createProduct:
    handler: src/handlers/productHandler.create
    events:
      - http:
          path: product
          method: post
          cors: true
  getProductById:
    handler: src/handlers/productHandler.getById
    events:
      - http:
          path: product/{id}
          method: get
          cors: true
  getProducts:
    handler: src/handlers/productHandler.getAll
    events:
      - http:
          path: product
          method: get
          cors: true

resources:
  Resources:
    DistributionCenterTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: distributionCenterId
            AttributeType: S
        KeySchema:
          - AttributeName: distributionCenterId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: DistributionCenterTable
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ProductTable
