# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ernestojv
# "service" is the name of this project. This will also be added to your AWS resource names.
service: dronofy-fc

stages:
  default:
    params:
      tableName: "DistributionCenterTable"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [DistributionCenterTable, Arn]
  environment:
    DISTRIBUTIONCENTER_TABLE: ${param:tableName}

functions:
  createDistributionCenter:
    handler: src/handlers/distributionCenterHandler.handler
    events:
      - http:
          path: distribution-centers
          method: get
          cors: true

resources:
  Resources:
    DistributionCenterTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: distributionCenterId
            AttributeType: S
        KeySchema:
          - AttributeName: distributionCenterId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: DistributionCenterTable
